name: HenRdp Premium

on:
  workflow_dispatch:

jobs:
  setup-tailscale:
    runs-on: windows-latest

    steps:
    - name: Download Background Image
      run: |
        Invoke-WebRequest -Uri "https://i.ibb.co/R26KsrY/20241207-204050.jpg" -OutFile "$env:USERPROFILE\Desktop\background.jpg"

    - name: Install Tailscale
      run: |
        Invoke-WebRequest -Uri "https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe" -OutFile "tailscale-installer.exe"
        Start-Process -FilePath "tailscale-installer.exe" -ArgumentList "/quiet", "/norestart" -NoNewWindow -Wait

    - name: Authenticate Tailscale with Secret Key
      run: |
        $env:TAILSCALE_AUTHKEY = ${{ secrets.TAILSCALE_AUTHKEY }}
        Start-Process -FilePath "$env:ProgramFiles\Tailscale\tailscale.exe" -ArgumentList "up", "--authkey", $env:TAILSCALE_AUTHKEY -Wait

    - name: Set Desktop Background
      run: |
        reg add "HKCU\Control Panel\Desktop" /v Wallpaper /t REG_SZ /d "$env:USERPROFILE\Desktop\background.jpg" /f
        reg add "HKCU\Control Panel\Desktop" /v WallpaperStyle /t REG_SZ /d "2" /f

    - name: Enable Audio
      run: |
        $audioRegistryPath = "HKCU:\Software\Microsoft\Windows\CurrentVersion\MMDevices\Audio\Render"
        
        # Memastikan path registry ada sebelum mengubah nilai
        if (Test-Path $audioRegistryPath) {
          Set-ItemProperty -Path $audioRegistryPath -Name "Mute" -Value 0
          Set-ItemProperty -Path $audioRegistryPath -Name "Volume" -Value 50
        } else {
          Write-Host "Audio registry path tidak ditemukan."
        }
        
        # Pastikan layanan AudioSrv berjalan
        $audioService = Get-Service -Name "AudioSrv"
        if ($audioService.Status -ne "Running") {
          Start-Service -Name "AudioSrv"
        }

    - name: Start RDP Service
      run: |
        reg add "HKLM\System\CurrentControlSet\Control\Terminal Server" /v fDenyTSConnections /t REG_DWORD /d 0 /f
        netsh advfirewall firewall set rule group="remote desktop" new enable=yes

    - name: Set Username and Password
      run: |
        net user administrator "HenCoders1234"
        net user administrator /active:yes

    - name: Enable Auto-Logon
      run: |
        reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /v AutoAdminLogon /t REG_SZ /d 1 /f
        reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /v DefaultUserName /t REG_SZ /d "administrator" /f
        reg add "HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon" /v DefaultPassword /t REG_SZ /d "HenCoders1234" /f

    - name: Configure RDP Performance Settings
      run: |
        reg add "HKCU\Software\Microsoft\Terminal Server Client" /v "DisableBackground" /t REG_DWORD /d 1 /f
        reg add "HKCU\Software\Microsoft\Terminal Server Client" /v "DisableFontSmoothing" /t REG_DWORD /d 1 /f
        reg add "HKCU\Software\Microsoft\Terminal Server Client" /v "DisableDesktopComposition" /t REG_DWORD /d 1 /f

    - name: Enable Clipboard Sharing
      run: |
        reg add "HKCU\Software\Microsoft\Terminal Server Client" /v "RedirectClipboard" /t REG_DWORD /d 1 /f

    - name: Enable RemoteFX for Graphics
      run: |
        reg add "HKCU\Software\Microsoft\Terminal Server Client" /v "RemoteFX" /t REG_DWORD /d 1 /f

    - name: Enable File and Printer Redirection
      run: |
        reg add "HKCU\Software\Microsoft\Terminal Server Client" /v "RedirectDrives" /t REG_DWORD /d 1 /f
        reg add "HKCU\Software\Microsoft\Terminal Server Client" /v "RedirectPrinters" /t REG_DWORD /d 1 /f

    - name: Enable Audit Logging for RDP
      run: |
        auditpol /set /subcategory:"Logon/Logoff" /success:enable /failure:enable

    - name: Change RDP Port (Optional for Security)
      run: |
        reg add "HKLM\SYSTEM\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp" /v PortNumber /t REG_DWORD /d 3390 /f

    - name: Display Tailscale IP
      run: |
        $tailscale_ip = & "$env:ProgramFiles\Tailscale\tailscale.exe" ip -4
        echo "Tailscale IP Address: $tailscale_ip"

    - name: Print RDP Info
      run: |
        echo "Host RDP: $tailscale_ip"
        echo "Username: administrator"
        echo "Password: HenCoders1234"

    - name: Keep Workflow Active with Status Log
      run: |
        $counter = 1
        $logNumber = 1
        $startTime = Get-Date
        while ($true) {
          $elapsedTime = (Get-Date) - $startTime
          $elapsedHours = [math]::Floor($elapsedTime.TotalHours)

          if ($elapsedHours % 5 -eq 0 -and $elapsedHours -gt 0) {
            echo "Logs $logNumber Active"
            echo "Logs $logNumber Status: Active"
            echo "Logs $logNumber Complete"
            $logNumber++
            $startTime = Get-Date
          }

          echo "HenRdp Active"
          Start-Sleep -Seconds 600
        }

    - name: Ensure Workflow Keeps Running (Even After 6 Hours)
      run: |
        $startTime = Get-Date
        while ($true) {
          $elapsedTime = (Get-Date) - $startTime
          echo "Workflow is running for $($elapsedTime.TotalHours) hours."
          Start-Sleep -Seconds 600
        }

    - name: Set Copyright Message on Desktop
      run: |
        $copyrightText = "©HenCoders Developer"
        $font = New-Object -TypeName System.Drawing.Font -ArgumentList "Arial", 16
        $brush = New-Object -TypeName System.Drawing.SolidBrush -ArgumentList [System.Drawing.Color]::White
        $bitmap = New-Object -TypeName System.Drawing.Bitmap -ArgumentList 1920,1080
        $graphics = [System.Drawing.Graphics]::FromImage($bitmap)
        $graphics.Clear([System.Drawing.Color]::Black)
        $graphics.DrawString($copyrightText, $font, $brush, [System.Drawing.PointF]::new(10, 10))
        $bitmap.Save("$env:USERPROFILE\Desktop\copyright_image.png")
        reg add "HKCU\Control Panel\Desktop" /v Wallpaper /t REG_SZ /d "$env:USERPROFILE\Desktop\copyright_image.png" /fyright_image.png" /f
