name: HenWindows 2022

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 9999

    steps:
    - name: Download start.bat
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/HenDeveloper/HenRdp2/refs/heads/main/start.bat -OutFile start.bat
    - name: Download loop.bat
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/HenDeveloper/HenRdp2/refs/heads/main/loop.bat -OutFile loop.bat
    - name: Install Tailscale
      run: |
        Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale-setup.exe
        Start-Process tailscale-setup.exe -ArgumentList "/quiet", "/norestart" -Wait
        $env:Path += ";C:\Program Files\Tailscale"  # Tambahkan path ke variabel lingkungan
    - name: Authenticate Tailscale
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey $Env:TAILSCALE_AUTHKEY
      env:
        TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
    - name: Enabling access to RDP
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Start RDP session
      run: cmd /c start.bat
    - name: Successfully made! You can close the tab now.
      run: cmd /c loop.bat
