name: HenWindows 2022

on: workflow_dispatch

jobs:
  build:
    runs-on: windows-2022
    timeout-minutes: 9999

    steps:
    - name: Download start.bat
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/HenDeveloper/HenRdp2/refs/heads/main/start.bat -OutFile start.bat
    - name: Download loop.bat
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/HenDeveloper/HenRdp2/refs/heads/main/loop.bat -OutFile loop.bat
    - name: Install Tailscale
      run: |
        Invoke-WebRequest -Uri https://pkgs.tailscale.com/stable/tailscale-setup-latest.exe -OutFile tailscale-setup.exe
        Start-Process tailscale-setup.exe -ArgumentList "/quiet", "/norestart" -Wait
        $env:Path += ";C:\Program Files\Tailscale"
    - name: Authenticate Tailscale
      run: |
        & "C:\Program Files\Tailscale\tailscale.exe" up --authkey $Env:TAILSCALE_AUTHKEY
      env:
        TAILSCALE_AUTHKEY: ${{ secrets.TAILSCALE_AUTHKEY }}
    - name: Install rclone
      run: |
        Invoke-WebRequest -Uri https://downloads.rclone.org/v1.68.2/rclone-v1.68.2-windows-amd64.zip -OutFile rclone.zip
        Expand-Archive rclone.zip -DestinationPath C:\rclone
        $env:Path += ";C:\rclone\rclone-v1.68.2-windows-amd64"
    - name: Add rclone to Path
      run: |
        [System.Environment]::SetEnvironmentVariable('Path', $env:Path, [System.EnvironmentVariableTarget]::Machine)
    - name: Configure rclone with Google Drive
      run: |
        C:\rclone\rclone-v1.68.2-windows-amd64\rclone.exe config create gdrive drive client_id="${{ secrets.GDRIVE_CLIENT_ID }}" client_secret="${{ secrets.GDRIVE_CLIENT_SECRET }}" scope="drive" root_folder_id="root" service_account_file=""
    - name: Enabling access to RDP
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server' -name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - name: Start RDP session
      run: cmd /c start.bat
    - name: Successfully made! You can close the tab now.
      run: cmd /c loop.bat
